### ISSUE TITLE
binary for OpenWrt Barrier Breaker 14.07-rc3 ?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mmaraya/port-mirroring#4]
```
Can you provide a compiled version of this port-mirroring tool for the current 
OpenWRT firmware images? Specifically for Barrier Breaker 14.07-rc3 on 
architecture    ar71xx? I would do it on my own, but I don't know how. Please.
```

Original issue reported on code.google.com by `martin.h...@gmail.com` on 21 Mar 2015 at 1:51

**Comment by mmaraya** [comment]
You can find a compiled version for the current stable version of OpenWrt, Chaos Calmer 15.05 at https://github.com/mmaraya/port-mirroring/releases/tag/1.4.1
