### ISSUE TITLE
Build for Atheros AR9344

### ISSUE THREAD

**Issue by pulgoso** [mmaraya/port-mirroring#50]
Could you post a binary for Atheros AR9344 platform. I am using Chaos Calmer 15.05. Kind regards.

**Comment by mmaraya** [comment]
I just checked the OpenWrt site and at least for the TP-Link [TL-WDR4300](https://wiki.openwrt.org/toh/tp-link/tl-wdr4300), the AR9344 platform also uses the "ar71xx" target so you should be able to use the current [binary](https://github.com/mmaraya/port-mirroring/releases/download/v1.4.2/port-mirroring_1.4.2_ar71xx.ipk). Could you please try it and let me know? In the meantime, I'll update the documentation to include AR9344. Thanks and sorry for the delay in getting back to you.

**Comment by pulgoso** [comment]
You are right, it works. I made a mistake when looking at wrong router. Lol. Sorry for the mixup, I can confirm it fully works using TEE option.
Kind regards
