### ISSUE TITLE
Need a manual restart to do the job

### ISSUE THREAD

**Issue by Pamac** [mmaraya/port-mirroring#55]
Hello,

When i start OpenWrt, the deamon is running but don't mirror any packet. 
If i manually stop / start the process everything work as expected. 
Any idea ?

Why did you choose priority 83 ?

OpenWrt IP : `192.168.1.1`

My config :
    `option 'target' '192.168.1.2'`
    `option 'source_ports' 'eth0,wlan0,wlan1'`
    `option 'filter' ''`
    `option 'promiscuous' '1'`
    `option 'protocol' 'TEE'`

**Comment by mmaraya** [comment]
Sorry for the late reply. I'm assuming you're using version 1.4.2-1 and will mark the daemon startup issues as a bug. As to the choice of 83, that was a design decision from the original developer and I'm not sure why that was selected. I imagine that was to ensure all the other init scripts ran before port-mirroring. Do you have a recommendation for what it should be?

**Comment by mmaraya** [comment]
Could not reproduce bug.
