### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by awwright** [mmaraya/port-mirroring#56]
The REAMDE has a section called "Build Prerequisites" but it would be helpful if there was a short overview on what I need to do to actually build a package.

For example, I'm targeting the `mvebu` arch (I think? /proc/cpuinfo lists `ARMv7 Processor rev 2 (v7l)`)

**Comment by mmaraya** [comment]
Excellent suggestion, I've added that as an enhancement and also flagged it as help wanted in case anyone wants to help out. I'll keep this issue open until it's resolved. Thanks!
