### ISSUE TITLE
No ipv6 mirroring

### ISSUE THREAD

**Issue by jasns** [mmaraya/port-mirroring#57]
Hi.

I have installed version 1.4.2 on a buffalo wzr-hp-g300nh, running  openwrt chaos calmer 15.05.1 (ar71xx-generic).

I can successfully mirror all ipv4 traffic from my br-lan interface, via TZSP to a remote server, but when I capture traffic on the remote server, I can't see any ipv6 traffic. My br-lan interface has ipv6 addresses, and I am successfully generating ipv6 traffic (ping6 ipv6.google.com).

How can I mirror ipv6 traffic?

Best Regards,

Jorge Santos

**Comment by mmaraya** [comment]
This was a suspected issue but thanks for confirming it. You can track progress via #52.
