### ISSUE TITLE
issu using TEE protocol

### ISSUE THREAD

**Issue by imenbhiri** [mmaraya/port-mirroring#59]
using the following config:
 config 'port-mirroring'
    option source_ports 'eth0.1'    
    option promiscuous  '1'             
    option target       'IP-address'   
    option protocol     'TEE'           #'TZSP'
I get the following error:
    daemon.err port-mirroring[32266]: error in recieved packet
    daemon.err port-mirroring[32266]: unable to read from socket: 'No such file or directory'
Did I miss something?

Regards,
Imen.

**Comment by mmaraya** [comment]
Sorry for the super late reply. port-mirroring must be run with root privileges and the interface 'eth0.1' must be valid. If this is still an issue, could you please confirm those two things and re-open this issue?
