### ISSUE TITLE
Add binaries for WRT1900ac

### ISSUE THREAD

**Issue by rcanzanese** [mmaraya/port-mirroring#63]
Requesting binaries for the WRT190ac.

If this request is as simple as building for and testing on this architecture, please let me know -- I would be able to do that on my own.

**Comment by mmaraya** [comment]
Apologies for the late reply as life has gotten in the way of my hobbies. https://openwrt.org/toh/linksys/linksys_wrt1900ac shows that this router uses the https://openwrt.org/docs/techref/targets/mvebu system on chip. Pick the right sub-architecture from https://downloads.openwrt.org/releases/18.06.2/targets/mvebu/ and follow the instructions on the README.md for building your ipk. Good luck!
