### ISSUE TITLE
support for openwrt 18.06

### ISSUE THREAD

**Issue by dummys** [mmaraya/port-mirroring#70]
Hello,
Do you plan to support openwrt 18.06 with AR9331 ?
Thanks

**Comment by Juniorlimaivd** [comment]
I also have this question

**Comment by mmaraya** [comment]
Yes, just been too busy at work but let me look at upgrading to 18.06 today.

**Comment by mmaraya** [comment]
Compiled against 18.06.2, please take a look and let me know if it works. Thanks!
